In [7]:
import pandas as pd
#file_path = r'C:\Users\abbychilds\Downloads\ot_delaycause1_DL(1)\Airline_Delay_Cause.csv'
df = pd.read_csv('Airline_Delay_Cause.csv')

In [10]:
import numpy as np
import pandas as pd
import duckdb

In [32]:
df.head(20)

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2026,7,9E,Endeavor Air Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",61.0,25.0,7.58,3.08,...,0.0,9.45,5.0,0.0,3034.0,941.0,937.0,211.0,0.0,945.0
1,2026,7,9E,Endeavor Air Inc.,ABY,"Albany, GA: Southwest Georgia Regional",92.0,34.0,10.01,1.19,...,0.0,17.72,2.0,1.0,3163.0,906.0,42.0,324.0,0.0,1891.0
2,2026,7,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",92.0,31.0,9.69,0.87,...,0.0,16.58,1.0,1.0,2613.0,668.0,150.0,123.0,0.0,1672.0
3,2026,7,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",205.0,77.0,28.98,6.17,...,0.0,31.88,7.0,0.0,6531.0,2280.0,717.0,605.0,0.0,2929.0
4,2026,7,9E,Endeavor Air Inc.,ALB,"Albany, NY: Albany International",93.0,26.0,9.63,0.00,...,0.0,14.84,7.0,0.0,2344.0,911.0,0.0,164.0,0.0,1269.0
5,2026,7,9E,Endeavor Air Inc.,ATL,"Atlanta, GA: Hartsfield-Jackson Atlanta Intern...",3025.0,928.0,182.23,53.49,...,1.0,475.59,91.0,29.0,96739.0,24403.0,6656.0,19423.0,18.0,46239.0
6,2026,7,9E,Endeavor Air Inc.,ATW,"Appleton, WI: Appleton International",86.0,17.0,4.72,0.04,...,0.0,11.33,2.0,1.0,1178.0,346.0,1.0,90.0,0.0,741.0
7,2026,7,9E,Endeavor Air Inc.,AUS,"Austin, TX: Austin - Bergstrom International",88.0,15.0,7.13,0.00,...,0.0,1.10,0.0,0.0,1009.0,454.0,0.0,423.0,0.0,132.0
8,2026,7,9E,Endeavor Air Inc.,AVL,"Asheville, NC: Asheville Regional",85.0,37.0,14.37,1.91,...,0.0,10.99,6.0,0.0,3279.0,844.0,224.0,1099.0,0.0,1112.0
9,2026,7,9E,Endeavor Air Inc.,BGR,"Bangor, ME: Bangor International",127.0,38.0,11.05,0.00,...,0.0,23.63,15.0,0.0,4530.0,2211.0,0.0,286.0,0.0,2033.0
10,2026,7,9E,Endeavor Air Inc.,BHM,"Birmingham, AL: Birmingham-Shuttlesworth Inter...",116.0,39.0,9.98,0.88,...,0.0,19.13,11.0,0.0,4020.0,1626.0,244.0,414.0,0.0,1736.0
11,2026,7,9E,Endeavor Air Inc.,BIS,"Bismarck/Mandan, ND: Bismarck Municipal",27.0,5.0,2.07,0.00,...,0.0,2.93,1.0,0.0,333.0,180.0,0.0,0.0,0.0,153.0
12,2026,7,9E,Endeavor Air Inc.,BMI,"Bloomington/Normal, IL: Central Il Regional Ai...",92.0,31.0,12.27,2.81,...,0.0,9.87,3.0,0.0,3026.0,1433.0,435.0,394.0,0.0,764.0
13,2026,7,9E,Endeavor Air Inc.,BNA,"Nashville, TN: Nashville International",271.0,73.0,21.92,1.86,...,0.0,29.47,37.0,3.0,6255.0,1642.0,162.0,1790.0,0.0,2661.0
14,2026,7,9E,Endeavor Air Inc.,BQK,"Brunswick, GA: Brunswick Golden Isles",92.0,30.0,9.66,1.03,...,0.0,14.66,3.0,1.0,2985.0,596.0,112.0,275.0,0.0,2002.0
15,2026,7,9E,Endeavor Air Inc.,BTR,"Baton Rouge, LA: Baton Rouge Metropolitan/Ryan...",44.0,24.0,5.41,2.86,...,0.0,12.66,2.0,1.0,2087.0,434.0,173.0,176.0,0.0,1304.0
16,2026,7,9E,Endeavor Air Inc.,BTV,"Burlington, VT: Patrick Leahy Burlington Inter...",212.0,63.0,34.24,0.00,...,0.0,23.05,19.0,0.0,6687.0,4269.0,0.0,435.0,0.0,1983.0
17,2026,7,9E,Endeavor Air Inc.,BUF,"Buffalo, NY: Buffalo Niagara International",230.0,49.0,12.24,0.00,...,0.0,26.60,36.0,0.0,4256.0,1117.0,0.0,662.0,0.0,2477.0
18,2026,7,9E,Endeavor Air Inc.,CAE,"Columbia, SC: Columbia Metropolitan",127.0,45.0,10.66,1.27,...,0.0,25.12,10.0,0.0,4029.0,1314.0,95.0,541.0,0.0,2079.0
19,2026,7,9E,Endeavor Air Inc.,CHA,"Chattanooga, TN: Lovell Field",214.0,72.0,26.33,1.94,...,0.0,34.64,14.0,1.0,8256.0,3195.0,188.0,1356.0,0.0,3517.0

In [14]:
airport_stats = duckdb.sql("""SELECT carrier_name, SUM(arr_del15) / SUM(arr_flights) as percent_delayed
                       FROM df
                       GROUP BY carrier_name
                       ORDER BY percent_delayed""").df()

print(airport_stats)

                               carrier_name  percent_delayed
0                        Mesa Airlines Inc.         0.160661
1                                 Envoy Air         0.184587
2             CommuteAir LLC dba CommuteAir         0.186034
3                          Republic Airline         0.221055
4   GoJet Airlines LLC d/b/a United Express         0.221289
5                   Alaska Airlines Network         0.229310
6                     SkyWest Airlines Inc.         0.234383
7                   Delta Air Lines Network         0.251211
8                         Piedmont Airlines         0.255180
9                  United Air Lines Network         0.258624
10                              Horizon Air         0.258796
11                        Endeavor Air Inc.         0.294567
12                       Southwest Airlines         0.302911
13                            Allegiant Air         0.304717
14                American Airlines Network         0.321188
15                        Frontier Airlines         0.337369
16                          JetBlue Airways         0.338367
17                        PSA Airlines Inc.         0.339387

In [18]:
airport_stats2 = duckdb.sql("""SELECT carrier_name, SUM(arr_del15) / SUM(arr_flights) as percent_delayed, SUM(carrier_ct) / (SUM(carrier_ct) + SUM(weather_ct) + SUM(nas_ct) + SUM(security_ct) + SUM(late_aircraft_ct)) as carrier_pt, SUM(weather_ct) / (SUM(carrier_ct) + SUM(weather_ct) + SUM(nas_ct) + SUM(security_ct) + SUM(late_aircraft_ct)) as weather_pt, SUM(nas_ct) / (SUM(carrier_ct) + SUM(weather_ct) + SUM(nas_ct) + SUM(security_ct) + SUM(late_aircraft_ct)) as nas_pt, SUM(security_ct) / (SUM(carrier_ct) + SUM(weather_ct) + SUM(nas_ct) + SUM(security_ct) + SUM(late_aircraft_ct)) as security_pt, SUM(late_aircraft_ct) / (SUM(carrier_ct) + SUM(weather_ct) + SUM(nas_ct) + SUM(security_ct) + SUM(late_aircraft_ct)) as late_aircraft_pt
                       FROM df
                       GROUP BY carrier_name
                       ORDER BY percent_delayed""").df()

print(airport_stats2)

                               carrier_name  percent_delayed  carrier_pt  \
0                        Mesa Airlines Inc.         0.160661    0.363821
1                                 Envoy Air         0.184587    0.226962
2             CommuteAir LLC dba CommuteAir         0.186034    0.313098
3                          Republic Airline         0.221055    0.257522
4   GoJet Airlines LLC d/b/a United Express         0.221289    0.233281
5                   Alaska Airlines Network         0.229310    0.266610
6                     SkyWest Airlines Inc.         0.234383    0.463666
7                   Delta Air Lines Network         0.251211    0.349359
8                         Piedmont Airlines         0.255180    0.194695
9                  United Air Lines Network         0.258624    0.260285
10                              Horizon Air         0.258796    0.199382
11                        Endeavor Air Inc.         0.294567    0.294338
12                       Southwest Airlines         0.302911    0.313727
13                            Allegiant Air         0.304717    0.230049
14                American Airlines Network         0.321188    0.275818
15                        Frontier Airlines         0.337369    0.220942
16                          JetBlue Airways         0.338367    0.292018
17                        PSA Airlines Inc.         0.339387    0.258613

    weather_pt    nas_pt  security_pt  late_aircraft_pt
0     0.041862  0.330948     0.000000          0.263368
1     0.079739  0.274382     0.002079          0.416838
2     0.046738  0.271382     0.000000          0.368781
3     0.042305  0.369927     0.000396          0.329849
4     0.031431  0.355621     0.000000          0.379666
5     0.025039  0.328179     0.004263          0.375909
6     0.091443  0.228017     0.000914          0.215961
7     0.039003  0.298832     0.000689          0.312118
8     0.069613  0.210223     0.000299          0.525170
9     0.024285  0.411930     0.000052          0.303449
10    0.012131  0.308716     0.001281          0.478490
11    0.037363  0.210662     0.000197          0.457441
12    0.019820  0.169362     0.003925          0.493165
13    0.095573  0.241683     0.003495          0.429200
14    0.042457  0.191266     0.001482          0.488977
15    0.026759  0.268781     0.000000          0.483519
16    0.023447  0.276491     0.002130          0.405915
17    0.060258  0.203501     0.001679          0.475949

In [31]:
airport_stats3 = duckdb.sql("""SELECT airport, SUM(arr_del15) / SUM(arr_flights) as percent_delayed, SUM(arr_del15), SUM (arr_flights) AS total_flights
                       FROM df
                       GROUP BY airport
                       ORDER BY total_flights""").df()

airport_stats3.tail(15)

    airport  percent_delayed  sum(arr_del15)  total_flights
352     DCA         0.331871          4162.0        12541.0
353     MCO         0.317712          4176.0        13144.0
354     BOS         0.314378          4174.0        13277.0
355     SFO         0.468159          6565.0        14023.0
356     LGA         0.290270          4123.0        14204.0
357     LAS         0.257971          3754.0        14552.0
358     IAH         0.206811          3073.0        14859.0
359     PHX         0.248979          4022.0        16154.0
360     LAX         0.239702          4219.0        17601.0
361     SEA         0.232623          4180.0        17969.0
362     CLT         0.257137          5215.0        20281.0
363     DFW         0.243632          6982.0        28658.0
364     DEN         0.243729          7190.0        29500.0
365     ATL         0.273750          8518.0        31116.0
366     ORD         0.244200          8621.0        35303.0

In [30]:
airport_stats4 = duckdb.sql("""SELECT airport, SUM(arr_del15) / SUM(arr_flights) as percent_delayed, SUM(carrier_ct) / (SUM(carrier_ct) + SUM(weather_ct) + SUM(nas_ct) + SUM(security_ct) + SUM(late_aircraft_ct)) as carrier_pt, SUM(weather_ct) / (SUM(carrier_ct) + SUM(weather_ct) + SUM(nas_ct) + SUM(security_ct) + SUM(late_aircraft_ct)) as weather_pt, SUM(nas_ct) / (SUM(carrier_ct) + SUM(weather_ct) + SUM(nas_ct) + SUM(security_ct) + SUM(late_aircraft_ct)) as nas_pt, SUM(security_ct) / (SUM(carrier_ct) + SUM(weather_ct) + SUM(nas_ct) + SUM(security_ct) + SUM(late_aircraft_ct)) as security_pt, SUM(late_aircraft_ct) / (SUM(carrier_ct) + SUM(weather_ct) + SUM(nas_ct) + SUM(security_ct) + SUM(late_aircraft_ct)) as late_aircraft_pt
                       FROM df
                       GROUP BY airport
                       ORDER BY percent_delayed"""
                    ).df()

airport_stats4.tail()
#observations - nas_pt is really high for SFO (San Francisco)! This can be explained as during July 2026, they had a major construction project which closed one of their runways

,airport,percent_delayed,carrier_pt,weather_pt,nas_pt,security_pt,late_aircraft_pt
362,SFO,0.468159,0.167936,0.017054,0.609908,0.000241,0.204861
363,SFB,0.474659,0.193306,0.119466,0.202115,0.000000,0.485113
364,DIK,0.481481,0.289615,0.038462,0.196923,0.000000,0.475000
365,ACY,0.509091,0.150357,0.096071,0.194643,0.000000,0.558929
366,PQI,0.645161,0.290500,0.000000,0.129000,0.000000,0.580500